"""Utility metrics for the World Cup prediction project.

- Provides `warmup_excluded_accuracy` which calculates the prediction
  accuracy **after ignoring each team's first match** (the warm‑up
  period).  This mirrors the manual calculation performed earlier and
  can be imported in notebooks, scripts, or the REPL.
"""

from __future__ import annotations

import polars as pl
from pathlib import Path


def _is_actual(status: str) -> bool:
    """Return ``True`` if the status column contains an ACTUAL result."""
    return status.startswith("ACTUAL")


def _parse_actual(status: str) -> tuple[str, str] | None:
    """Parse ``status_or_prediction`` like ``"ACTUAL: Mexico (Model: Mexico)"``.

    Returns a tuple ``(actual_outcome, model_prediction)`` or ``None`` if the
    format does not match.
    """
    import re

    m = re.match(r"ACTUAL: ([^(]+) \(Model: (.+)\)", status)
    if not m:
        return None
    actual_res = m.group(1).strip()
    model_pred = m.group(2).strip()
    return actual_res, model_pred


def _outcome_from_score(row: pl.Row) -> str | None:
    """Derive the true match outcome (home win, away win or Draw) from scores.

    Returns ``"Draw"`` for a tie, the home team name for a home win, the away
    team name for an away win, or ``None`` if scores are missing.
    """
    sh = row["score_home"]
    sa = row["score_away"]
    if sh == "" or sa == "":
        return None
    sh = int(sh)
    sa = int(sa)
    if sh > sa:
        return row["team_home"]
    if sh < sa:
        return row["team_away"]
    return "Draw"


def _model_outcome(row: pl.Row, model_pred: str) -> str:
    """Normalise the model prediction to one of ``"Draw"`` or a team name.

    The CSV stores either a plain team name (e.g., ``"Brazil"``) or a more
    descriptive string such as ``"Draw/Tight Match (-0.3)"``.  If the string
    contains the word ``Draw`` we treat it as a draw; otherwise we look for the
    home or away team name inside the string.  As a fallback the first token
    is returned.
    """
    if "Draw" in model_pred:
        return "Draw"
    if row["team_home"] in model_pred:
        return row["team_home"]
    if row["team_away"] in model_pred:
        return row["team_away"]
    return model_pred.split()[0]


def warmup_excluded_accuracy(
    csv_path: str | Path = "data/predictions.csv",
    matches_path: str | Path = "data/matches.csv",
) -> float:
    """Calculate accuracy **ignoring each team's first match** *and* any tactical matches.

    Parameters
    ----------
    csv_path:
        Path to the ``predictions.csv`` file generated by ``predict.py``.
    matches_path:
        Path to ``matches.csv`` which contains the ``is_tactical`` flag.

    Returns
    -------
    float
        Accuracy as a fraction (e.g., ``0.75`` for 75 %).
    """
    # Load predictions and keep only ACTUAL rows
    df = pl.read_csv(csv_path, try_parse_dates=True)
    df = df.filter(pl.col("status_or_prediction").str.starts_with("ACTUAL"))

    # Load matches to fetch the tactical flag and join on match_id
    matches = pl.read_csv(matches_path, try_parse_dates=True)
    # Ensure match_id column types align (both int)
    matches = matches.with_columns(pl.col("match_id").cast(pl.Int64))
    df = df.join(matches.select(["match_id", "is_tactical"]), on="match_id", how="left")

    # Exclude tactical matches (is_tactical == 1)
    df = df.filter(pl.col("is_tactical") != 1)

    # Identify the first non‑tactical match for each team (by date, then match_id)
    home = df.select([
        pl.col("match_id"),
        pl.col("date"),
        pl.col("team_home").alias("team"),
    ])
    away = df.select([
        pl.col("match_id"),
        pl.col("date"),
        pl.col("team_away").alias("team"),
    ])
    long = pl.concat([home, away])
    long = long.sort(["team", "date", "match_id"], descending=False)
    first_per_team = long.group_by("team").agg(pl.col("match_id").first().alias("first_match_id"))
    first_match_ids = set(first_per_team["first_match_id"].to_list())

    # Exclude the first match of each team (warm‑up period)
    df = df.filter(~pl.col("match_id").is_in(first_match_ids))

    # Compute correctness for the remaining rows
    def _is_correct(row: pl.Row) -> bool:
        parsed = _parse_actual(row["status_or_prediction"])
        if not parsed:
            return False
        _, model_pred = parsed
        true_outcome = _outcome_from_score(row)
        if true_outcome is None:
            return False
        model_out = _model_outcome(row, model_pred)
        return true_outcome == model_out

    # Compute correctness with a simple Python loop (Polars apply on rows is cumbersome)
    correct = 0
    for row in df.iter_rows(named=True):
        if _is_correct(row):
            correct += 1
    total = df.height
    return correct / total if total else 0.0


if __name__ == "__main__":
    acc = warmup_excluded_accuracy()
    print(f"Warm‑up‑excluded accuracy: {acc:.2%} ({int(acc*100)} % )")
